### ISSUE TITLE
Feature: Convert Grafana dashboards to KubeSphere monitoring templates

### ISSUE THREAD

**Issue by huanggze** [kubesphere/monitoring-dashboard#7]
Grafana is a successful and widely used observability tool.  In future releases, we should support importing dashboards from Grafana dashboard templates. It can be implemented with a binary handing this conversion.

**Comment by benjaminhuo** [comment]
Contributors are welcomed to create this tool 
KubeSphere custom dashboard template samples and their corresponding grafana dashboard linkscan be found in https://github.com/kubesphere/monitoring-dashboard/tree/master/contrib/gallery
